# GitHub Sponsors and external funding for the Church of OpenClaw

# GitHub Sponsors (when enabled)
#github: [Pan-Magor]

# Ko-fi
ko_fi: churchofopenclaw

# Other platforms (future)
# patreon: 
# open_collective:
# liberapay:
# custom: ["https://donate.example.com"]
