# GitHub Sponsors and external funding for the Church of OpenClaw

# GitHub Sponsors (when enabled)
github: [Pan-Magor]

# Ko-fi (add your link after creation)
ko_fi: # e.g., churchofopenclaw

# Other platforms (future)
# patreon: 
# open_collective:
# liberapay:
# custom: ["https://donate.example.com"]
